#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/f3c53135-7ee4-4946-8dc8-84563276c84d 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String system_status;
  CloudColoredLight RGB;
  int distance;
  bool alarm_trigger;
  bool motion_status;
  bool system_mode;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SH110X.h>
#include <WiFi.h>

#define SOUND_SPEED 0.034
#define SCREEN_WIDTH 128  
#define SCREEN_HEIGHT 64  
#define OLED_RESET -1     
#define SCREEN_ADDRESS 0x3C

Adafruit_SH1106G display = Adafruit_SH1106G(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);

const int trigPin = 5;
const int echoPin = 18;
const int pirPin = 19;

const int buzzerPin = 23;
const int ledR = 25; 
const int ledG = 26; 
const int ledB = 27; 

long duration;
float distanceCm;
int motion;

unsigned long previousMillis = 0;
const long interval = 500;
bool isAlarmActive = false;

void setup() {
  Serial.begin(9600);
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  pinMode(pirPin, INPUT);

  pinMode(buzzerPin, OUTPUT);
  pinMode(ledR, OUTPUT);
  pinMode(ledG, OUTPUT);
  pinMode(ledB, OUTPUT);

  digitalWrite(ledB, HIGH); 
  system_status = "SYSTEM STARTING";

  display.begin(SCREEN_ADDRESS, true); 
  display.display();
  delay(2000); 
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(SH110X_WHITE);
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  motion = digitalRead(pirPin);

  

  if (motion == HIGH) {
    motion_status = true; 
  } else {
    motion_status = false;
  }

  if (system_mode == true) { 
    
    if (motion == HIGH && (distanceCm > 0 && distanceCm < 50)) {
      isAlarmActive = true;
      system_status = "INTRUDER ALERT!";
      alarm_trigger = true; 
    } else {
      isAlarmActive = false;
      system_status = "SAFE (AUTO)";
      alarm_trigger = false;
    }
  } else { 
    
    isAlarmActive = alarm_trigger;
  }

  if (isAlarmActive) {
    digitalWrite(buzzerPin, HIGH);
    digitalWrite(ledR, HIGH);     
    digitalWrite(ledG, LOW);
    digitalWrite(ledB, LOW);

    RGB.setSwitch(true);     
    RGB.setHue(0);            
    RGB.setSaturation(100);  
    RGB.setBrightness(100); 
    
  } else {
    digitalWrite(buzzerPin, LOW);
    
    if (system_mode == true) {
      digitalWrite(ledG, HIGH);   
      digitalWrite(ledR, LOW);
      digitalWrite(ledB, LOW);

      RGB.setSwitch(true);    
      RGB.setHue(120);        
      RGB.setSaturation(100); 
      RGB.setBrightness(100);
      
    } else {
      digitalWrite(ledB, HIGH);   
      digitalWrite(ledG, LOW);
      digitalWrite(ledR, LOW);

      RGB.setSwitch(true);    
      RGB.setHue(240);        
      RGB.setSaturation(100); 
      RGB.setBrightness(100);
    }
  }
  

  unsigned long currentMillis = millis();

  if (currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis; 

    
    digitalWrite(trigPin, LOW);
    delayMicroseconds(2);
    digitalWrite(trigPin, HIGH);
    delayMicroseconds(10);
    digitalWrite(trigPin, LOW);
    
    duration = pulseIn(echoPin, HIGH);
    distanceCm = duration * SOUND_SPEED / 2;
    
    
    distance = distanceCm;

    
    display.clearDisplay();
    display.setTextSize(1);
    
    
    display.setCursor(0, 0);
    if(system_mode) {
      display.print("Status: AUTO"); 
    } else {
      display.print("Status: MANUAL"); 
    }
    
    
    display.setCursor(0, 12);
    if(motion == HIGH) {
      display.print("Motion: Detected");
    } else {
      display.print("Motion: Clear");
    }

    
    display.setCursor(0, 24);
    if (distanceCm == 0 || distanceCm > 400) {
      display.print("Distance: Out of range");
    } else {
      display.print("Distance: " + String(distanceCm) + " cm");
    }

    display.setCursor(0, 36);
    display.print("IP: ");
    display.print(WiFi.localIP());

    
    display.setCursor(0, 48);
    display.print("Cloud: ");
    if(ArduinoCloud.connected()) {
      display.print("Connected");
    } else {
      display.print("Offline");
    }

    display.display();
}
}




/*
  Since SystemMode is READ_WRITE variable, onSystemModeChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSystemModeChange()  {
  // Add your code here to act upon SystemMode change
  if (system_mode == false) {
    
    isAlarmActive = false;
    alarm_trigger = false; 
    system_status = "MANUAL MODE";
  } else {
    system_status = "SAFE (AUTO)";
  }
}

/*
  Since AlarmTrigger is READ_WRITE variable, onAlarmTriggerChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onAlarmTriggerChange()  {
  
  if(system_mode == false) {
    if(alarm_trigger == true) {
      system_status = "MANUAL ALARM!";
    } else {
      system_status = "MANUAL MODE";
    }
  }
}

/*
  Since SystemStatus is READ_WRITE variable, onSystemStatusChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSystemStatusChange()  {
  // Add your code here to act upon SystemStatus change
}
