// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "1b66bbf0-eea3-4f4d-a832-a8eaaeabb395";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSystemStatusChange();
void onAlarmTriggerChange();
void onSystemModeChange();

String system_status;
CloudColoredLight RGB;
int distance;
bool alarm_trigger;
bool motion_status;
bool system_mode;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(system_status, READWRITE, ON_CHANGE, onSystemStatusChange);
  ArduinoCloud.addProperty(RGB, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(distance, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(alarm_trigger, READWRITE, ON_CHANGE, onAlarmTriggerChange);
  ArduinoCloud.addProperty(motion_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(system_mode, READWRITE, ON_CHANGE, onSystemModeChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
